/**
 * This file was automatically generated by Nerest.
 * DO NOT MODIFY IT BY HAND. Instead, modify the source schema.json file,
 * and run "nerest typegen" to regenerate this file.
 */

/**
 * Renders website's header with countdown
 */
export interface HeaderProps {
  countdownSeconds: number;
  affirmation?: string;
  [k: string]: unknown;
}
